# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=42)),
                ('prenom', models.CharField(max_length=42)),
                ('photo', models.ImageField(upload_to='photos/')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('password', models.CharField(max_length=100)),
                ('ecole', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
