# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='age',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
