# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0004_auto_20161122_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='is_student',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
