# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0005_profil_is_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('boulot', models.CharField(max_length=50)),
                ('annonce', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de dépôt')),
                ('prix', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lieux', models.CharField(max_length=50)),
                ('trajet', models.BooleanField()),
                ('distance_max', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('annonceur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profils.Profil')),
            ],
        ),
    ]
