# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 13:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0006_annonce'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='trajet',
        ),
    ]
