# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 16:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0007_remove_annonce_trajet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonce',
            name='boulot',
        ),
    ]
