# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0008_remove_annonce_boulot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='annonceur',
            field=models.CharField(max_length=100),
        ),
    ]
