# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0010_auto_20161201_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='sexe',
            field=models.CharField(default='homme', max_length=10),
            preserve_default=False,
        ),
    ]
