# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profils', '0011_profil_sexe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
